'use strict';
const {steps,upload,notice,escape}=require('../ui/page');
const {HEADERS}=require('./jobs');
function createCreationView({canApply=()=>true}={}){return {
 canApply,
 form(res,{controls}){return `${steps(['Upload Source Courses','Validate & Confirm','Create Source Courses'])}<form method="post" action="/create/preview">${controls(res,'preview')}<div class="form-grid"><div class="panel">${upload('create',HEADERS.join(','),'Each row needs a Source Course name and code, plus exactly one Course Template ID or code.')}</div><aside class="panel guidance"><span class="eyebrow">Before you begin</span><h3>Bulk Source Course Creator</h3><ul class="explanation"><li><strong>Use an existing Course Template</strong><p>Every Source Course is created as a child of the verified template.</p></li><li><strong>Review before creating</strong><p>Validation checks templates and codes without creating courses. Valid rows can continue when other rows have issues.</p></li><li><strong>Creation is permanent</strong><p>Created courses are not rolled back. Uncertain requests are never sent again automatically.</p></li></ul></aside></div><div class="action-bar"><button class="primary">2. Validate & Confirm</button></div></form>`;},
 render(res,job,{controls,button,now}){const active=['validating','planning','queued','running'].includes(job.status),ready=job.status==='ready',rows=job.rows||[],tasks=job.tasks||[],summary=job.creationSummary||{};const count=status=>summary[status==='eligible'?'eligible':status]??rows.filter(r=>r.status===status).length;const created=summary.created??tasks.filter(t=>t.result?.status==='created').length,registrationPending=summary.registrationPending??tasks.filter(t=>t.result?.status==='created'&&t.result.registration!=='ready').length,failed=summary.failed??tasks.filter(t=>t.result?.status==='failed').length,uncertain=summary.uncertain??tasks.filter(t=>t.result?.status==='uncertain').length,notAttempted=summary.notAttempted??tasks.filter(t=>t.result?.status==='notAttempted').length,processed=(job.totals?.created||0)+(job.totals?.skipped||0)+(job.totals?.failed||0)+(job.totals?.uncertain||0)+(job.totals?.notAttempted||0),total=summary.total??tasks.length,elapsed=Math.max(0,(job.step3ElapsedMs||0)+(job.step3StartedAt?Math.max(0,(job.step3ProgressAt||now())-job.step3StartedAt):0)),step2Elapsed=Math.max(0,(job.step2ElapsedMs||0)+(job.step2StartedAt?Math.max(0,(job.step2ProgressAt||now())-job.step2StartedAt):0)),fmt=ms=>`${Math.floor(ms/60000)}m ${Math.floor(ms%60000/1000)}s`,remaining=(done,total,elapsed)=>done>=3&&elapsed>=15000&&done<total?fmt(Math.max(0,(total-done)*(elapsed/done))):'Calculating ETA…';
  const progress=ready||!job.confirmedAt?`<section class="panel"><h2>Validation results</h2><div class="metrics">${[[count('eligible'),'Eligible'],[count('skipped'),'Skipped'],[count('invalid'),'Invalid']].map(([n,l])=>`<div><strong>${n}</strong><span>${l}</span></div>`).join('')}</div>${job.progress?.phase==='templates'&&active?`<p>${job.progress.processed||0} of ${job.progress.total||total||rows.length} rows validated · Elapsed: ${fmt(step2Elapsed)} · ${remaining(job.progress.processed||0,job.progress.total||rows.length,step2Elapsed)}</p>`:''}</section>`:`<section class="panel date-progress apply-progress"><h2>Creation progress</h2><p>${processed} of ${total} eligible rows processed</p><progress max="${total||1}" value="${processed}"></progress><div class="apply-counters"><div><strong>${created}</strong><span>Created</span></div><div><strong>${registrationPending}</strong><span>Registration pending</span></div><div><strong>${count('skipped')}</strong><span>Skipped</span></div><div><strong>${failed}</strong><span>Failed</span></div><div><strong>${uncertain}</strong><span>Uncertain</span></div><div><strong>${notAttempted}</strong><span>Not attempted</span></div></div><p>Elapsed: ${fmt(elapsed)} · ${processed<total?remaining(processed,total,elapsed):'Complete'}</p></section>`;
  const confirm=ready&&job.expiresAt>now()?`<section class="confirmation"><h2>Ready to create Source Courses</h2><p>Only eligible rows will be submitted. Invalid and existing-code rows remain in the report.</p><form method="post" action="/create/apply">${controls(res,'apply',job._id)}<label class="checkbox"><input type="checkbox" name="confirmCreation" value="yes" required> I confirm creating the eligible Source Courses.</label><button class="primary">3. Create Source Courses</button></form></section>`:'';
  return `${steps(['Upload Source Courses','Validate & Confirm','Create Source Courses'],ready?1:job.confirmedAt?2:0)}<div class="metrics">${[[job.rows.length,'CSV rows'],[total,'Eligible'],[created,'Created']].map(([n,l])=>`<div><strong>${n}</strong><span>${l}</span></div>`).join('')}</div>${progress}${job.message?notice(job.message,job.status==='failed'?'warning':'default'):''}${confirm}${active?'<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><p>Processing saved progress. This page refreshes every 10 seconds.</p></div>':''}<div class="toolbar">${button(res,'report',job._id,'Download results CSV')}${['validating','planning','ready'].includes(job.status)||job.confirmedAt&&active?button(res,'cancel',job._id,'Cancel'):''}${active?button(res,'status',job._id,'Refresh status','id="create-refresh"'):''}</div>${active?'<script>setTimeout(()=>document.getElementById("create-refresh").requestSubmit(),10000);</script>':''}`;
 },
 report(job){const rows=[['SourceCourseName','SourceCourseCode','TemplateId','TemplateCode','CreatedOrgUnitId','Status','Message']];for(const row of job.rows||[]){const task=(job.tasks||[]).find(t=>t.row===row.row),result=task?.result,status=result?.status||(job.confirmedAt?'notAttempted':row.status),message=row.message||result?.message||(status==='notAttempted'?'Not started because the job was cancelled.':'');rows.push([row.sourceCourseNameInput??row.sourceCourseName,row.sourceCourseCodeInput??row.sourceCourseCode,task?.TemplateId||row.templateIdInputRaw||row.templateIdInput,row.templateCodeInput??row.templateCode,result?.CreatedOrgUnitId||'',status,message]);}return '\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');}
};}
module.exports={createCreationView};
