'use strict';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusNames={copiesInProcess:'Copies in process',copiesConcluded:'Copies concluded',validating:'Checking courses',planning:'Checking courses',ready:'Ready for review',queued:'Queued',running:'Processing',submitted:'Deployment submitted',submittedWithErrors:'Some deployments need attention',outcomeUnknown:'Check deployment outcome',activated:'Replicas active',activationWithErrors:'Activation needs attention',completed:'Dates updated',completedWithErrors:'Completed with issues',failed:'Needs attention',interrupted:'Processing interrupted',reviewed:'Reviewed — courses released',cancelled:'Cancelled',valid:'Valid',invalid:'Invalid',notAttempted:'Not attempted',pending:'Pending',duplicate:'Duplicate',updated:'Updated',unchanged:'Unchanged',skipped:'Skipped',uncertain:'Check outcome'};
function badge(status){const tone=['copiesConcluded','completed','activated','updated','valid','unchanged'].includes(status)?'success':['failed','invalid','interrupted','uncertain','outcomeUnknown','activationWithErrors','completedWithErrors','submittedWithErrors'].includes(status)?'warning':'neutral';return `<span class="badge ${tone}">${escape(statusNames[status]||status||'Pending')}</span>`;}
function steps(items,current=0){return `<ol class="steps" aria-label="Workflow progress">${items.map((label,i)=>`<li class="${i===current?'current':i<current?'done':''}" ${i===current?'aria-current="step"':''}><span>${i+1}</span>${escape(label)}</li>`).join('')}</ol>`;}
function table(headings,rows,empty='No results yet.'){return rows.length?`<div class="table-scroll" tabindex="0" role="region" aria-label="${escape(headings.join(', '))}"><table><thead><tr>${headings.map(h=>`<th scope="col">${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table>`:`<div class="empty-state">${escape(empty)}</div>`;}
function upload(id,headers,description){return `<div class="upload-box"><span class="eyebrow">${id==='bulk'?'Source course list':'Source courses and replicas list'}</span><h3>Upload your CSV</h3><p>${escape(description)}</p><label class="file-label" for="${id}-file">Choose a CSV file</label><input id="${id}-file" type="file" required accept=".csv,text/csv" data-csv-target="${id}-csv" data-max-bytes="5242880"><p id="${id}-message" class="muted" role="status">UTF-8 CSV · up to 10,000 rows · 5 MB</p><a download="${id}-template.csv" href="data:text/csv;charset=utf-8,${encodeURIComponent(headers+'\r\n')}">Download CSV template</a></div><textarea id="${id}-csv" name="csv" hidden></textarea>`;}
function notice(message,type='default'){return `<d2l-alert type="${type}">${escape(message)}</d2l-alert>`;}
function workspace({dates,replication,history,selected='dates'}) {
 const items=[['dates','Bulk Activity Dates Manager','▦',dates],['replication','Bulk Source Courses Deployer','▤',replication],['history','Job History','◷',history]];
 return `<div class="sidebar-layout"><aside class="sidebar"><nav aria-label="Course operations">${items.map(([id,label,icon])=>`<a href="#${id}" data-section="${id}" ${id===selected?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}</a>`).join('')}</nav></aside><div class="workspace-content">${items.map(([id,label,icon,body])=>`<section id="pane-${id}" ${id===selected?'':'hidden'} aria-label="${label}">${body}</section>`).join('')}</div></div>`;
}
function workflowSidebar(content,{ltik,section}){
 const items=[['dates','Bulk Activity Dates Manager','▦'],['replication','Bulk Source Courses Deployer','▤'],['history','Job History','◷']];
 return `<div class="sidebar-layout"><aside class="sidebar"><nav aria-label="Course operations">${items.map(([id,label,icon])=>`<form method="post" action="/workspace"><input type="hidden" name="ltik" value="${escape(ltik)}"><input type="hidden" name="section" value="${id}"><button type="submit" data-sidebar-native ${id===section?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}</button></form>`).join('')}</nav></aside><div class="workspace-content">${content}</div></div>`;
}
function page(content,{ltik='',section='dates',language='en'}={}){
 if(ltik&&!content.includes('class="sidebar-layout"'))content=workflowSidebar(content,{ltik,section});
 return `<!doctype html><html lang="en" data-ui-language="${escape(language)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Brightspace Source Courses Tools</title><link rel="stylesheet" href="/assets/app.css"><script type="module" src="/assets/app.js"></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="app-header"><div class="brand"><span class="brand-mark" aria-hidden="true">B</span><div><strong>Brightspace Source Courses Tools</strong><span>Bulk Activity Dates Manager and Bulk Source Courses Deployer</span></div></div><label class="language-picker">Language<select data-language-selector aria-label="Language / Idioma"><option value="en">English</option><option value="es-419">Español (Latinoamérica)</option><option value="pt-BR">Português (Brasil)</option></select></label></header><main id="main" tabindex="-1">${content}</main></body></html>`;}
module.exports={escape,badge,steps,table,upload,notice,workspace,page,statusNames};
