'use strict';
const {escape,steps,upload,notice}=require('../ui/page');
const {DEFAULT_ZONE,ZONES}=require('./timeZone');
const date=(value,timeZone=DEFAULT_ZONE)=>value?new Intl.DateTimeFormat('pt-BR',{timeZone,dateStyle:'short',timeStyle:'medium'}).format(new Date(value)):'No date';
function createDateView({writeEnabled}){return {
 form(res,{controls,button}){const values=res.locals?.dateForm||{};return `<section id="date-management">${steps(['Upload Source Courses','Review Updates','Apply and Update'])}<form method="post" action="/bulk/preview" id="bulk-input">${controls(res,'preview')}<div class="form-grid"><div class="panel">${upload('bulk','OrgUnitId,OrgUnitCode','Provide a source course ID, code, or matching ID/code pair per row. Duplicate source courses are processed once.')}</div><aside class="panel guidance"><span class="eyebrow">Before you begin</span><h3>Bulk Activity Dates Manager</h3><ul class="explanation"><li><strong>Course Mapping</strong><p>Use IDs, codes, or both. If both are supplied, they must match.</p></li><li><strong>What will change</strong><p>The same dates apply to assignments, quizzes, and discussion topics in every listed course.</p></li><li><strong>Review first</strong><p>Review the changes before applying. Fix any course or identifier errors to continue.</p></li></ul></aside></div><div class="panel date-schedule"><span class="eyebrow">Schedule</span><h3>Choose the new dates</h3><div class="date-schedule-fields"><label class="field">Time zone<select name="timeZone" required style="display:block;width:100%;margin-top:7px">${ZONES.map(zone=>`<option value="${escape(zone)}" ${zone===(values.timeZone||DEFAULT_ZONE)?'selected':''}>${escape(zone===DEFAULT_ZONE?'Brasília — America/Sao_Paulo':zone.replaceAll('_',' '))}</option>`).join('')}</select></label>${['start','due','end'].map(k=>`<label class="field">${k[0].toUpperCase()+k.slice(1)} date and time<input type="datetime-local" name="${k}" step="1" value="${escape(values[k]||'')}" required></label>`).join('')}</div><p class="muted">Start must be before Due. End must be on or after Due.</p></div><div class="action-bar date-upload-actions"><button class="primary">2. Review Updates</button></div></form></section>`;},
 render(res,job,{button,now,page=1}){
 const review=job.status==='ready';
 const success=job.status==='completed'&&job.tasks.length>0&&job.tasks.every(t=>['updated','unchanged'].includes(t.result?.status));
 const checking=['validating','planning'].includes(job.status);
 const updating=['queued','running'].includes(job.status);
 const updated=job.tasks.filter(t=>t.result?.status==='updated').length;
 const unchanged=job.tasks.filter(t=>t.result?.status==='unchanged').length;
 const timeZone=job.timeZone||DEFAULT_ZONE;
 const active=['validating','planning','queued','running'].includes(job.status),permitted=job.tasks.every(t=>writeEnabled(t.activity.type));
 const stage=['validating','planning'].includes(job.status)?0:job.status==='ready'?1:2;
 const issues=job.tasks.filter(t=>['failed','skipped','uncertain'].includes(t.result?.status)).length+job.rows.filter(r=>r.status==='invalid').length+job.courses.filter(c=>c.status==='invalid').length;
 const outcomes={
 cancelled:['Job Cancelled','This job was cancelled before activity date updates started.'],
 failed:['Needs Attention','The job could not complete. Download the CSV report to review the issues before starting a new job.'],
 completedWithErrors:['Completed with Issues',`${updated} activities were updated and ${unchanged} already had the requested dates. Some activities could not be updated. Download the CSV report for details.`],
 interrupted:['Processing Interrupted','Processing stopped before completion. Some dates may have changed. Review the CSV report before starting another job.'],
 completed:['Needs Attention','The saved results do not confirm that all activities have the requested dates. Download the CSV report for details.']
 };
 const outcome=!success&&outcomes[job.status];
 const detail=job.message||job.rows.find(r=>r.status==='invalid'&&r.message)?.message||job.courses.find(c=>c.status==='invalid'&&c.message)?.message||job.tasks.find(t=>t.result?.error?.message)?.result.error.message;
 const outcomeBox=outcome?`<section class="confirmation ${job.status==='cancelled'?'neutral-confirmation':'warning-confirmation'}" role="status"><h2>${escape(outcome[0])}</h2><p>${escape(outcome[1])}</p>${detail?`<p>${escape(detail)}</p>`:''}</section>`:'';
 return `<div data-date-job hidden></div>${steps(['Upload Source Courses','Review Updates','Apply and Update'],stage)}<div class="metrics"><div><strong>${job.courses.length}</strong><span>Courses</span></div><div><strong>${job.tasks.length}</strong><span>Activities</span></div><div><strong>${issues}</strong><span>Need attention</span></div></div>${outcomeBox}<section class="panel"><h2>${success?'Updated Dates':'Requested Dates'} <small>${escape(timeZone)}</small></h2><div class="date-summary">${['start','due','end'].map(k=>`<div><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${escape(date(job.dates[k],timeZone))}</strong></div>`).join('')}</div></section>${success?`<section class="confirmation success-confirmation" role="status"><h2>✓ Activity Dates Updated</h2><p>${updated?`Updated dates for <strong>${updated} ${updated===1?'activity':'activities'}</strong>. `:''}${unchanged?`<strong>${unchanged} ${unchanged===1?'activity already had':'activities already had'}</strong> the requested dates. `:''}All <strong>${job.tasks.length} ${job.tasks.length===1?'activity':'activities'}</strong> across <strong>${job.courses.length} source ${job.courses.length===1?'course':'courses'}</strong> now have the requested dates, updated in Brightspace.</p></section>`:''}
 ${job.status==='ready'&&job.expiresAt>now()&&permitted?`<section class="confirmation"><h2>Ready to apply</h2><p>This will update all <strong>${job.tasks.length} ${job.tasks.length===1?'activity':'activities'}</strong> in <strong>${job.courses.length} source ${job.courses.length===1?'course':'courses'}</strong>. Confirm the requested dates above before continuing.</p><div class="confirmation-actions">${button(res,'apply',job._id,'3. Apply & Update')}</div></section>`:''}
 ${job.status==='ready'&&!permitted?notice('Apply is unavailable. Configure the required write scopes for every activity type in this plan.','warning'):''}${job.status==='ready'&&job.expiresAt<=now()?notice('This preview expired. Select Bulk Activity Dates Manager in the sidebar and create a new preview.','warning'):''}
 ${active?`<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>${updating?'Updating your Source Courses':'Checking your Source Courses'}</strong><p>Results refresh every 10 seconds. You can close this page and return through Job history.</p></div></div>`:''}
 <div class="toolbar">${button(res,'status',job._id,'Refresh status',`id="job-refresh" data-page="${page}"`)}${button(res,'report',job._id,'Download CSV report')}${['validating','ready','queued'].includes(job.status)?button(res,'cancel',job._id,'Cancel this job'):''}</div>
 ${active?'<script>setTimeout(()=>document.getElementById("job-refresh").requestSubmit(),10000);</script>':''}`;
 }
};}
module.exports={createDateView};
