'use strict';
const {diagnosticText}=require('./diagnostics');
const {targetStatus,canActivateTarget}=require('./outcomes');
const {escape,badge,steps,table,upload,notice}=require('../ui/page');
function createDeploymentView({enabled}){return {
 canApply:()=>enabled(),
 form(res,{controls,button}){return `<section id="source-replication">${steps(['Upload Mappings','Review & Deploy','Confirm completion','Activate'])}<form method="post" action="/deploy/preview">${controls(res,'preview')}<div class="form-grid"><div class="panel">${upload('deploy','SourceOrgUnitId,ReplicaOrgUnitId','Provide both IDs on each row. Repeat a source course ID to deploy it to several replicas.')}</div><aside class="panel guidance"><span class="eyebrow">Before you begin</span><h3>A fresh copy for every replica</h3><ol class="explanation"><li><strong>Prepare</strong><p>Replicas are made inactive before deployment.</p></li><li><strong>Deploy</strong><p>Brightspace resets replica content and copies the source.</p></li><li><strong>Activate later</strong><p>Check completion in Brightspace, then return here to activate every replica.</p></li></ol></aside></div><div class="action-bar date-upload-actions"><button class="primary">2. Review & Deploy</button></div></form></section>`;},
 render(res,job,{controls,button,now}){
 const active=['validating','planning','queued','running'].includes(job.status),activating=job.operation==='activate';
 const results=job.tasks.flatMap(t=>t.targets.map(target=>({task:t,sourceId:t.sourceId,sourceName:t.sourceName,target,...(t.result||t.preview),status:t.result?.targets?.find(r=>r.orgUnitId===target.orgUnitId)?.status||t.result?.status||'pending'})));
 const stage=job.status==='activated'||activating?3:['submitted','submittedWithErrors','outcomeUnknown'].includes(job.status)?2:job.status==='ready'||job.status==='running'||job.status==='queued'?1:0;
 const canActivate=['submitted','submittedWithErrors','outcomeUnknown','interrupted','failed','activationWithErrors'].includes(job.status)&&job.tasks.some(t=>t.targets.some(r=>canActivateTarget(t,r)));
 return `<div class="section-heading"><div><span class="eyebrow">Source replication</span><h1>${stage===0?'Check your course mappings':stage===1?'Review your deployment':stage===2?'Check copy completion':'Activate your replicas'}</h1></div>${badge(job.status)}</div>${steps(['Upload Mappings','Review & Deploy','Confirm completion','Activate'],stage)}<div class="metrics"><div><strong>${new Set(job.tasks.map(t=>t.sourceId)).size}</strong><span>Sources</span></div><div><strong>${results.length}</strong><span>Replicas</span></div><div><strong>${results.filter(r=>['updated','unchanged'].includes(r.target.activation?.status)).length}</strong><span>Verified active</span></div></div>
 ${job.tasks.some(t=>t.result)?`<section class="panel"><h2>Deployment Results</h2><div class="deployment-outcomes">${[['submitted','Submitted'],['failed','Failed'],['uncertain','Uncertain'],['notAttempted','Not attempted']].map(([status,label])=>`<div><strong>${results.filter(r=>targetStatus(r.task,r.target)===status).length}</strong><span>${label}</span></div>`).join('')}</div><p>Submitted means accepted for copying. Check completion in Brightspace before activation.</p></section>`:''}
 ${job.message?notice(job.message,['activated','submitted'].includes(job.status)?'default':'warning'):''}
 ${job.status==='ready'&&job.expiresAt>now()&&enabled()?`<section class="confirmation"><h2>Confirm replacement of replica content</h2><p>The app will prepare and submit one batch at a time. Isolated failures do not block other batches. They stay inactive until you return to activate them.</p><form method="post" action="/deploy/apply">${controls(res,'apply',job._id)}<label class="checkbox"><input type="checkbox" name="confirmReset" value="yes" required> I confirm Brightspace will reset all ${results.length} listed replicas and replace their content from the listed sources.</label><button class="primary">Prepare and deploy</button></form></section>`:''}
 ${job.status==='ready'&&!enabled()?notice('Deployment unavailable. Configure manageCourses:deploy:manage and orgunits:course:update (or matching wildcards), plus Service User permissions.','warning'):''}
 ${job.status==='ready'&&job.expiresAt<=now()?notice('Preview expired. Return to Workspace and validate your mappings again.','warning'):''}
 ${active?`<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>${job.status==='running'?(activating?'Activating and verifying replicas':'Preparing replicas and submitting deployment'):'Checking your mappings'}</strong><p>This page refreshes every 10 seconds. You can return through Job history.</p></div></div>`:''}
 ${canActivate?`<section class="confirmation"><h2>Copying finished in Brightspace?</h2><p>There is no automatic copy progress here. Check every submitted or uncertain replica in Brightspace and confirm that its copy finished before continuing. Only replicas with submitted or uncertain deployments will be activated after your confirmation. Failed and not-attempted replicas are excluded; inspect any left inactive during preparation.</p><form method="post" action="/deploy/activate">${controls(res,'activate',job._id)}<label class="checkbox"><input type="checkbox" name="confirmCompleted" value="yes" required> I have verified that every submitted or uncertain copy has finished, no such deployment is still running, and those replicas are ready to activate.</label><button class="primary">Activate replicas</button></form></section>`:''}
 ${['submitted','submittedWithErrors','outcomeUnknown','interrupted','failed','activationWithErrors'].includes(job.status)?`<section class="panel"><h2>Resolve this job</h2><p>After checking Brightspace, close this job to release its course reservations. This does not deploy, activate, or restore any course. Saved results remain available.</p><form method="post" action="/deploy/review">${controls(res,'review',job._id)}<label class="checkbox"><input type="checkbox" name="confirmReviewed" value="yes" required> I checked all affected courses in Brightspace, confirmed no copy is still running, and reviewed any inactive or incomplete replicas.</label><button>Mark reviewed and release courses</button></form></section>`:''}
 <div class="toolbar">${button(res,'status',job._id,'Refresh submission status','id="deploy-refresh"')}${button(res,'report',job._id,'Download submission report')}${button(res,'history','','My deployment jobs')}${!activating&&['validating','ready','queued'].includes(job.status)?button(res,'cancel',job._id,'Cancel'):''}</div>
 <details class="panel" ${job.rows.some(r=>r.status==='invalid')?'open':''}><summary>CSV validation · ${job.rows.length} rows</summary>${table(['Row','Source ID','Replica ID','Status','Details'],job.rows.map(r=>[escape(r.row),escape(r.sourceId),escape(r.targetId),badge(r.status),escape(r.message||'—')]))}</details>
 <section class="panel"><h2>Sources and replicas</h2>${job.tasks.map(t=>`<div class="source-group"><h3>${escape(t.sourceName)} <small>Source ID ${escape(t.sourceId)}</small></h3>${table(['Replica','Initially active','Preparation','Deployment','Activation'],results.filter(r=>r.task===t).map(r=>[`<strong>${escape(r.target.name)}</strong><small>ID ${escape(r.target.orgUnitId)}</small>${r.target.activation?.error||r.target.deactivation?.error||r.error?`<p class="row-error">${escape([r.error,r.target.deactivation?.error,r.target.activation?.error].filter(Boolean).map(diagnosticText).join(' | '))}</p>`:''}`,r.target.isActive?'Yes':'No',r.target.deactivation?(['updated','unchanged'].includes(r.target.deactivation.status)?'<span class="badge success">Inactive · verified</span>':badge(r.target.deactivation.status)):'Not started',r.status==='ready'||r.status==='pending'?'Not submitted':badge(r.status),r.target.activation?(['updated','unchanged'].includes(r.target.activation.status)?'<span class="badge success">Active · verified</span>':badge(r.target.activation.status)):'Not activated']))}</div>`).join('')||'<p class="empty-state">Mappings will appear after validation.</p>'}</section>
 <details class="technical"><summary>Job details and deployment IDs</summary><p>Job ${escape(job._id)}</p><p>Submitted means accepted for processing, not verified completion.</p>${table(['Source ID','Deployment ID'],job.tasks.map(t=>[escape(t.sourceId),escape(t.result?.deploymentId||'Not submitted')]))}</details>${active?'<script>setTimeout(()=>document.getElementById("deploy-refresh").requestSubmit(),10000);</script>':''}`;
 },
  report(job){
   const rows=[['CSV row','Source ID','Replica ID','Source name','Replica name','Validation','Submission status','Deployment ID','Details','Deactivation','Activation','Deployment HTTP status','Brightspace error details','Request/correlation ID']];
   for(const row of job.rows){const task=job.tasks.find(t=>t.sourceId===row.sourceId&&t.targets.some(target=>target.orgUnitId===row.targetId)),r=task?.result;rows.push([row.row,row.sourceId,row.targetId,row.sourceName,row.targetName,row.status,task?targetStatus(task,{orgUnitId:row.targetId}):'notAttempted',r?.deploymentId,[row.message,r?.error?.message,task?.targets.find(t=>t.orgUnitId===row.targetId)?.deactivation?.error?.message].filter(Boolean).join(' '),task?.targets.find(t=>t.orgUnitId===row.targetId)?.deactivation?.status,task?.targets.find(t=>t.orgUnitId===row.targetId)?.activation?.status,r?.error?.httpStatus,r?.error?.responseDetails,r?.error?.requestId]);}
   return '\uFEFF'+rows.map(row=>row.map(value=>{let v=String(value??'');if(/^\s*[=+\-@]|^[\t\r\n]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');
  }
 };
}
module.exports={createDeploymentView};
