'use strict';
const {targetStatus}=require('./outcomes');
const {escape,steps,upload,notice}=require('../ui/page');
function createDeploymentView({enabled}){return {
 canApply:()=>enabled(),
 form(res,{controls,button}){return `<section id="source-replication">${steps(['Upload Mappings','Review & Confirm','Deploy and Check'])}<form method="post" action="/deploy/preview">${controls(res,'preview')}<div class="form-grid"><div class="panel">${upload('deploy','SourceOrgUnitId,ReplicaOrgUnitId','Provide both IDs on each row. Repeat a source course ID to deploy it to several replicas.')}</div><aside class="panel guidance"><span class="eyebrow">Before you begin</span><h3>Source Courses Replication</h3><ul class="explanation"><li><strong>Course Mapping</strong><p>Map each replica to its source course in your CSV file.</p></li><li><strong>Source Deployment</strong><p>Replicas are made inactive before deployment. Brightspace resets their content and starts a complete copy from the mapped source course.</p></li><li><strong>Course Activation and Copy Completion</strong><p>Replicas accepted for deployment are reactivated automatically. Use “Check copy results now” in Job History to review their copy logs.</p></li></ul></aside></div><div class="action-bar date-upload-actions"><button class="primary">2. Review & Confirm</button></div></form></section>`;},
 render(res,job,{controls,button,now}){
 const checkingCopies=['queued','running'].includes(job.copyCheck?.status);
 const active=['validating','planning','queued','running'].includes(job.status),activating=job.operation==='activate';
 const results=job.tasks.flatMap(t=>t.targets.map(target=>({task:t,sourceId:t.sourceId,sourceName:t.sourceName,target,...(t.result||t.preview),status:t.result?.targets?.find(r=>r.orgUnitId===target.orgUnitId)?.status||t.result?.status||'pending'})));
 const stage=job.reactivationFinishedAt||activating||job.tasks.some(t=>t.result)||['queued','running','activated','activationWithErrors'].includes(job.status)?2:job.status==='ready'?1:0;
 const canActivate=!active&&job.tasks.some(t=>t.targets.some(r=>targetStatus(t,r)==='submitted'&&!['updated','unchanged'].includes(r.activation?.status)));
 const eligible=results.filter(r=>['submitted','uncertain'].includes(targetStatus(r.task,r.target)));
 const copied=eligible.filter(r=>job.copyMonitor?.[r.target.orgUnitId]?.status==='Copied successfully').length;
 const activated=results.filter(r=>['updated','unchanged'].includes(r.target.activation?.status)).length;
 const allCopied=results.length>0&&copied===results.length;
 const progress=job.copyCheck&&!checkingCopies?`<p role="status">${checkingCopies?'Checking copy results':'Last check'}: ${job.copyCheck.processed} of ${job.copyCheck.total} replicas checked.</p>`:'';
 const terminal=!active&&job.status!=='ready';
 const successful=job.status==='activated';
 return `${steps(['Upload Mappings','Review & Confirm','Deploy and Check'],stage)}<div class="metrics deployment-metrics"><div><strong>${new Set(job.tasks.map(t=>t.sourceId)).size}</strong><span>Source Courses</span></div><div><strong>${results.length}</strong><span>Replicas</span></div><div><strong>${copied}</strong><span>Copied Successfully</span></div><div><strong>${eligible.length-copied}</strong><span>Copy in Process</span></div></div>
 ${checkingCopies?`<p class="muted">Last saved results — updated as this check progresses.</p><div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>Checking copy results in Brightspace</strong><p>${job.copyCheck.processed} of ${job.copyCheck.total} replicas checked. This page refreshes automatically. You can return through Job History.</p></div></div>`:''}
 ${terminal&&!checkingCopies?`<section class="confirmation ${successful?'success-confirmation':job.status==='cancelled'?'neutral-confirmation':'warning-confirmation'}"><h2>${successful?(allCopied?'✓ Courses Copied Successfully':'✓ Deployment Submitted'):job.status==='cancelled'?'Deployment Cancelled':job.status==='submitted'?'Deployment Submitted':'Deployment Needs Attention'}</h2><p>${successful?(allCopied?`All ${copied} replicas were copied successfully and reactivated.`:`${activated} replicas reactivated. Check copy results to confirm completion.`):escape(job.message||'Review the submission report for validation, deployment, and activation results.')}</p>${eligible.length&&!allCopied?'<p>Unconfirmed copies may still be queued, running, or awaiting results.</p>':''}${progress}<p>Per-course details are available in the CSV report.</p></section>`:job.message&&!checkingCopies?notice(job.message,'warning'):''}
 ${job.status==='ready'&&job.expiresAt>now()&&enabled()?`<section class="confirmation"><h2>Ready to deploy</h2><p>The app will prepare and submit one batch at a time. Isolated failures do not block other batches. Accepted replicas are automatically reactivated while copying may still be queued or running.</p><form method="post" action="/deploy/apply">${controls(res,'apply',job._id)}<label class="checkbox"><input type="checkbox" name="confirmReset" value="yes" required> I confirm Brightspace will reset all ${results.length} replicas and replace their content from the mapped source courses.</label><button class="primary">3. Deploy and Check</button></form></section>`:''}
 ${job.status==='ready'&&!enabled()?notice('Deployment unavailable. Configure manageCourses:deploy:manage and orgunits:course:update (or matching wildcards), plus Service User permissions.','warning'):''}
 ${job.status==='ready'&&job.expiresAt<=now()?notice('Preview expired. Return to Workspace and validate your mappings again.','warning'):''}
 ${active?`<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>${job.status==='running'?(activating?'Activating and verifying replicas':'Preparing replicas and submitting deployment'):'Checking your mappings'}</strong><p>This page refreshes every 10 seconds. You can return through Job history.</p></div></div>`:''}
 ${canActivate?`<section class="confirmation"><h2>Retry reactivation</h2><p>This retries only activation for accepted replicas. It does not submit another deployment.</p><form method="post" action="/deploy/activate">${controls(res,'activate',job._id)}<button class="primary">Retry reactivation</button></form></section>`:''}
 <div class="toolbar">${eligible.length&&!active&&!checkingCopies?button(res,'checkCopies',job._id,'Check copy results now'):''}${!terminal?button(res,'status',job._id,'Refresh submission status','id="deploy-refresh"'):''}${button(res,'report',job._id,'Download submission report')}${!activating&&['validating','ready','queued'].includes(job.status)?button(res,'cancel',job._id,'Cancel'):''}</div>
 ${terminal&&checkingCopies?`<form method="post" action="/deploy/status" id="deploy-refresh" hidden>${controls(res,'status',job._id)}</form>`:''}
 ${active||checkingCopies?'<script>setTimeout(()=>document.getElementById("deploy-refresh").requestSubmit(),10000);</script>':''}`;
 },
  report(job){
   const rows=[['CSV row','Source ID','Replica ID','Source name','Replica name','Validation','Submission status','Deployment ID','Details','Deactivation','Activation','Deployment HTTP status','Brightspace error details','Request/correlation ID','Copy monitoring','Copy logs','Copy last checked UTC','Current check status']];
   for(const row of job.rows){const task=job.tasks.find(t=>t.sourceId===row.sourceId&&t.targets.some(target=>target.orgUnitId===row.targetId)),r=task?.result;rows.push([row.row,row.sourceId,row.targetId,row.sourceName,row.targetName,row.status,task?targetStatus(task,{orgUnitId:row.targetId}):'notAttempted',r?.deploymentId,[row.message,r?.error?.message,task?.targets.find(t=>t.orgUnitId===row.targetId)?.deactivation?.error?.message].filter(Boolean).join(' '),task?.targets.find(t=>t.orgUnitId===row.targetId)?.deactivation?.status,task?.targets.find(t=>t.orgUnitId===row.targetId)?.activation?.status,r?.error?.httpStatus,r?.error?.responseDetails,r?.error?.requestId,job.copyMonitor?.[row.targetId]?.status||'Not checked',job.copyMonitor?.[row.targetId]?.details,job.copyMonitor?.[row.targetId]?.checkedAt?new Date(job.copyMonitor[row.targetId].checkedAt).toISOString():'',job.copyCheck?job.copyMonitor?.[row.targetId]?.runId===job.copyCheck.runId?'Checked': 'Pending current check':'Not requested']);}
   return '\uFEFF'+rows.map(row=>row.map(value=>{let v=String(value??'');if(/^\s*[=+\-@]|^[\t\r\n]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');
  }
 };
}
module.exports={createDeploymentView};
