'use strict';
const {escape,steps,upload,notice}=require('../ui/page');
const {COMPONENTS,HEADERS,terminalCopy}=require('./jobs');
const LABELS={AttendanceRegisters:'Attendance registers',CompletionTracking:'Completion tracking',CourseAppearance:'Course appearance',CourseFiles:'Course files',DisplaySettings:'Display settings',Dropbox:'Assignments',Faq:'FAQ',Forms:'Registration forms',GradesSettings:'Grade settings',IntelligentAgents:'Intelligent agents',LearningOutcomes:'Learning outcomes',LtiLink:'LTI links',LtiTP:'LTI tool providers',Navbars:'Navigation bars',News:'Announcements',QuestionLibrary:'Question library',ReleaseConditions:'Release conditions',S3Model:'S3 model',SelfAssessments:'Self assessments',ToolNames:'Tool names'};
const label=c=>LABELS[c]||c;
function createCopyView(){return {
 canApply:()=>true,
 form(res,{controls}){const state=res.locals.dateForm||{},mode=state.copyMode||'all',chosen=[state.components||[]].flat();return `${steps(['Upload Mappings','Review & Confirm','Start Copy & Check'])}<form method="post" action="/copy/preview">${controls(res,'preview')}<div class="form-grid copy-upload-grid"><div class="panel">${upload('copy',HEADERS.join(','),'Provide an ID or code for each origin and destination. If both are provided, they must identify the same course.')}</div><aside class="panel guidance"><span class="eyebrow">Before you begin</span><h3>Bulk Course Copy to Source Courses</h3><ul class="explanation"><li><strong>Components to Copy</strong><p>Copy all or selected components from a Course Offering to an existing Course Offering or Source Course.</p></li><li><strong>Keep in mind</strong><p>Existing content stays in place, so copies may create duplicates. Courses are not created or activated.</p></li><li><strong>Check the results</strong><p>Invalid mappings are skipped. Review errors and copy results in the CSV report.</p></li></ul></aside></div><section class="panel"><h2>Components to Copy</h2><label class="checkbox"><input type="radio" name="copyMode" value="all" ${mode==='all'?'checked':''}> Copy all components</label><label class="checkbox"><input type="radio" name="copyMode" value="selected" ${mode==='selected'?'checked':''}> Copy selected components</label><div data-copy-selection ${mode==='selected'?'':'hidden'}><p>Selected components will apply to all courses mapped in the CSV.</p><div class="copy-components">${COMPONENTS.map(c=>`<label class="checkbox"><input type="checkbox" name="components" value="${c}" ${chosen.includes(c)?'checked':''}> ${escape(label(c))}</label>`).join('')}</div></div></section><div class="action-bar copy-upload-actions"><button class="primary">2. Review & Confirm</button></div></form>`;},
 render(res,job,{controls,button,now}){
  const active=['validating','planning','queued','running'].includes(job.status),ready=job.status==='ready';
  const successful=job.tasks.filter(t=>t.result?.status==='COMPLETE').length,pending=job.tasks.filter(t=>['PENDING','PROCESSING'].includes(t.result?.status)).length;
  const stage=ready?1:job.confirmedAt?2:0;
  const validating=['validating','planning'].includes(job.status);
  const processingTitle=validating?'Validating course mappings':job.operation==='check'?'Checking copy results in Brightspace':'Submitting copy requests';
  const processingProgress=validating?`Validating mappings: ${job.progress?.processed||0} of ${job.rows.length}.`:'';
  const issues=job.tasks.filter(t=>t.result&& !['COMPLETE','PENDING','PROCESSING'].includes(t.result.status)).length;
  const tone=job.status==='copiesConcluded'||(job.status==='copiesInProcess'&&!issues)?'success-confirmation':job.status==='cancelled'?'neutral-confirmation':'warning-confirmation';
  const title=job.status==='copiesConcluded'?'✓ Courses Copied Successfully':job.status==='cancelled'?'Copy Cancelled':job.status==='copiesInProcess'&&!issues?'✓ Copy Submitted':'Copy Needs Attention';
  const summary=job.status==='copiesConcluded'?`All ${successful} destinations were copied successfully.`:job.status==='cancelled'?'This job was cancelled. Review the report for any previously submitted copies.':job.status==='copiesInProcess'&&!issues?`${pending} destinations initiated copy. Check copy results to confirm completion.`:'Review the report for validation issues, failed copies, or unconfirmed submissions.';

  return `${steps(['Upload Mappings','Review & Confirm','Start Copy & Check'],stage)}<div class="metrics deployment-metrics">${[[new Set(job.tasks.map(t=>t.originId)).size,'Origin Courses'],[job.tasks.length,'Destination Courses'],[successful,'Copied Successfully'],[pending,'Copies in Process']].map(([v,k])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}</div><section class="panel"><h2>Components to Copy</h2><p>${job.components===null?'Copy all components':job.components.map(c=>`<span>${escape(label(c))}</span>`).join(' · ')}</p></section>
  ${job.rows.some(r=>r.status==='invalid')&& !['validating','planning','ready'].includes(job.status)?notice('Some mappings were excluded and were not submitted. See the CSV report for details.','warning'):''}
 ${active?`<div class="processing" role="status"><d2l-loading-spinner size="24"></d2l-loading-spinner><div><strong>${processingTitle}</strong>${processingProgress?`<p>${escape(processingProgress)}</p>`:''}<p>This page refreshes automatically. You can return through Job History.</p></div></div>`:''}
  ${ready&&job.expiresAt>now()?`<section class="confirmation"><h2>Ready to copy</h2>${job.rows.some(r=>r.status==='invalid')?'<p>Some mappings were excluded. Download the report to review errors before continuing.</p>':''}<p>Copying into a course that already contains content can create duplicates. Review the mappings and selected components before continuing.</p><form method="post" action="/copy/apply">${controls(res,'apply',job._id)}<label class="checkbox"><input type="checkbox" name="confirmCopy" value="yes" required> I confirm copying the selected components into these destinations.</label><button class="primary">3. Start Copy & Check</button></form></section>`:''}
  ${ready&&job.expiresAt<=now()?notice('Preview expired. Return to Workspace and validate your mappings again.','warning'):''}
  ${!active&&!ready?`<section class="confirmation ${tone}"><h2>${title}</h2><p>${escape(summary)}</p>${issues&&successful?`<p>${successful} destinations were copied successfully.</p>`:''}${pending?'<p>Unconfirmed copies may still be queued, running, or awaiting results.</p>':''}${job.message?`<p>${escape(job.message)}</p>`:''}<p>Per-course details are available in the CSV report.</p></section>`:''}
  <div class="toolbar">${!active&&job.tasks.some(t=>t.result?.jobToken&&!terminalCopy.has(t.result.status))?button(res,'checkCopies',job._id,'Check copy results now'):''}${button(res,'report',job._id,'Download copy report')}${['validating','planning','ready'].includes(job.status)?button(res,'cancel',job._id,'Cancel'):''}${active?button(res,'status',job._id,'Refresh status','id="copy-refresh"'):''}</div>${active?'<script>setTimeout(()=>document.getElementById("copy-refresh").requestSubmit(),10000);</script>':''}`;
 },
 report(job){
  const rows=[['CSV row',...HEADERS,'Origin name','Destination name','Validation','Copy status','Job token','Components','Copy last checked UTC','Details']];
  for(const row of job.rows){const r=job.tasks.find(t=>t.row===row.row)?.result;rows.push([row.row,row.originId,row.originCode,row.destinationId,row.destinationCode,row.originName,row.destinationName,row.status,r?.status||'notAttempted',r?.jobToken,job.components?.join(';')||'ALL',r?.checkedAt?new Date(r.checkedAt).toISOString():'',[row.message,r?.message].filter(Boolean).join(' ')]);}
  return '\uFEFF'+rows.map(row=>row.map(v=>{let s=String(v??'');if(/^\s*[=+\-@]|^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');
 }
};}
module.exports={createCopyView,LABELS};
